# action.yml
name: 'Commit-Issue-Action'
author: 'wescran'
description: 'Create an issue when a commit is made on a repository'
inputs:
  sourceRepo:
    description: 'Repository to watch for commits to'
    required: true
  targetRepo:
    description: 'Repository to create issues in'
    required: true
  issueLabels:
    description: 'Comma-with-space separated labels for the issue'
    required: false
  timeUntil:
    description: 'Only commits before this date will be found, in epoch(seconds). Defaults to current date'
    required: false
  timeFrame:
    description: 'Time, in Unix time(seconds), to look back from timeUntil for commits. Defaults to 1 hour ago'
    required: false
outputs:
  issueURL:
    description: 'The html url of the created issue'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.sourceRepo }}
    - ${{ inputs.targetRepo }}
    - ${{ inputs.issueLabels }}
    - ${{ inputs.timeUntil }}
    - ${{ inputs.timeFrame }}
branding:
  icon: 'git-commit'
  color: 'green'
